trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Authenticate to Azure Artifacts
- task: PipAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'
  inputs:
    artifactFeeds: 'python-packages-test'  # Your feed name
    onlyAddExtraIndex: false

# Step 2: Install dependencies (test that packages download)
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Step 3: Run the app (simple test)
- script: |
    python app.py
  displayName: 'Run application'

# Step 4: Build Docker image
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: 'test:latest'