trigger:
  - main

pool:
  name: 'Default'  # Changed from vmImage to name (self-hosted pool)



steps:
# Step 1: Authenticate to Azure Artifacts
- task: PipAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'
  inputs:
    artifactFeeds: 'python-packages-test'
    onlyAddExtraIndex: true


- script: |
    # Create and activate a virtual environment
    python -m venv venv_dir
    source venv_dir/bin/activate  # For Linux/macOS
    # .\venv_dir\Scripts\Activate.ps1  # Use this for PowerShell on Windows
    # .\venv_dir\Scripts\activate.bat  # Use this for cmd on Windows

    # Update pip inside the virtual environment
    python -m pip install --upgrade pip

    # Install dependencies into the virtual environment
    pip install --no-cache-dir -r requirements.txt

    # (Optional) Deactivate the virtual environment at the end of the script
    # deactivate
  displayName: 'Install dependencies in venv'

# Step 3: Run the app
- script: |
    python app.py
  displayName: 'Run application'

# Step 4: Build Docker image (if you have Docker installed locally)
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: 'test:latest'
    arguments: '--build-arg PIP_INDEX_URL="$(PIP_INDEX_URL)"'

