trigger:
  - main

pool:
  name: 'Default'  # Changed from vmImage to name (self-hosted pool)



steps:
# Step 1: Authenticate to Azure Artifacts
- task: PipAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'
  inputs:
    artifactFeeds: 'python-packages-test'
    onlyAddExtraIndex: false

#Step 2: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Step 3: Run the app
- script: |
    python app.py
  displayName: 'Run application'

# Step 4: Build Docker image (if you have Docker installed locally)
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: 'test:latest'
    arguments: '--build-arg PIP_INDEX_URL=https://python-packages-test:$(ARTIFACTS_PAT)@pkgs.dev.azure.com/chetanrana/secplayground/_packaging/python-packages-test/pypi/simple/'