trigger:
  - main

pool:
  name: 'Default'  # self-hosted pool

steps:
- powershell: |
    try {
      python -V
      pip --version
    } catch {
      Write-Error "Python or pip not found in PATH on this agent."
      exit 1
    }
  displayName: 'Verify Python present on self-hosted agent'

- task: PipAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'
  inputs:
    artifactFeeds: 'python-packages-test'
    onlyAddExtraIndex: false

- powershell: |
    python -m venv venv_dir

    # Use the venv pip directly (avoids activation / execution policy issues)
    & .\venv_dir\Scripts\pip.exe install --upgrade pip

    # Install using the index Azure Artifacts published to the environment
    & .\venv_dir\Scripts\pip.exe install --no-cache-dir --index-url "$env:PIP_INDEX_URL" -r requirements.txt
  displayName: 'Create venv and install dependencies (using Azure Artifacts index)'

- powershell: |
    Write-Host "PIP_INDEX_URL=$env:PIP_INDEX_URL"
    & .\venv_dir\Scripts\python.exe -V
    & .\venv_dir\Scripts\pip.exe --version
    # Quick verification: show which index is used when downloading a package (no install)
    & .\venv_dir\Scripts\pip.exe download --no-deps --no-cache-dir -v requests -d .\pip_check || Write-Host "pip download exit $LASTEXITCODE"
  displayName: 'Verify pip index and venv'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: 'test:latest'
    arguments: '--build-arg PIP_INDEX_URL=$(PIP_INDEX_URL)'

