trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    set -e
    python -V
    pip --version
  displayName: 'Verify Python present on agent'

- task: PipAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'
  inputs:
    artifactFeeds: 'secplayground/python-packages-test'
    

- script: |
    set -e
    python -m venv venv_dir
    ./venv_dir/bin/pip install --upgrade pip
    # Rely on PIP_INDEX_URL exported by PipAuthenticate (no explicit --index-url)
    ./venv_dir/bin/pip install --no-cache-dir -r requirements.txt
  displayName: 'Create venv and install dependencies (using Azure Artifacts index)'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: 'test:latest'
    arguments: '--build-arg PIP_INDEX_URL=https://python-packages-test:$(AZURE_ARTIFACTS_TOKEN)@pkgs.dev.azure.com/secplayground/_packaging/python-packages-test/pypi/simple/'   
    


